/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ayame
 */
public class IssueBook extends javax.swing.JFrame {

    /** 
     * Creates new form ManageBooks
     */
    
    public IssueBook() {
        initComponents();
    }
    
    public void getUserDetails() {
        int userId = Integer.parseInt(txt_userId.getText());
        
        try {
            Connection con = ConexaoBanco.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from user_details where user_id = ?");
            pst.setInt(1, userId);
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                user_id.setText(rs.getString("user_id"));
                user_name.setText(rs.getString("name"));
                
                user_invalid.setText("");
                
            } else {
                user_invalid.setText("Usuário inválido");
                         
                user_id.setText("");
                user_name.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void getBookDetails() {
        int bookId = Integer.parseInt(txt_bookId.getText());
        
        try {
            Connection con = ConexaoBanco.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from book_details where id = ?");
            pst.setInt(1, bookId);
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                book_id.setText(rs.getString("id"));
                book_title.setText(rs.getString("name"));
                book_author.setText(rs.getString("author"));
                book_quantity.setText(rs.getString("quantity"));
                
                book_invalid.setText("");
            } else {
                book_invalid.setText("Livro inválido");
                
                book_id.setText("");
                book_title.setText("");
                book_author.setText("");
                book_quantity.setText(""); 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public int issueBook() {
        int bookId = Integer.parseInt(txt_bookId.getText());
        int userId = Integer.parseInt(txt_userId.getText());
        String bookName = book_title.getText();
        String userName = user_name.getText();
        
        java.util.Date uissueDate = issueDate.getDatoFecha();
        java.util.Date udueDate = dueDate.getDatoFecha();
        
        java.sql.Date sissueDate = new java.sql.Date(uissueDate.getTime());
        java.sql.Date sdueDate = new java.sql.Date(udueDate.getTime());
        
        try {
            Connection con = ConexaoBanco.getConnection();
            
            String sql = "insert into issue_book_details(book_id, book_name, student_id, student_name, issue_date, due_date, status) values (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setInt(1, bookId);
            pst.setString(2, bookName);
            pst.setInt(3, userId);
            pst.setString(4, userName);
            pst.setDate(5, sissueDate);
            pst.setDate(6, sdueDate);
            pst.setString(7, "pending");
            
            int rowCount = pst.executeUpdate();
            
            if (rowCount > 0) {
                return 1;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return 0;
    }
    
    public void updateBookCount() {
        int bookId = Integer.parseInt(txt_bookId.getText());
        
        try {
            Connection con = ConexaoBanco.getConnection();
            String sql = "update book_details set quantity = quantity - 1 where id = ?";
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, bookId);
            
            int rowCount = pst.executeUpdate();
            
            if (rowCount > 0) {
                int initialCount = Integer.parseInt(book_quantity.getText());
                book_quantity.setText(Integer.toString(initialCount - 1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book_id = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        book_title = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        book_author = new app.bolivia.swing.JCTextField();
        jLabel17 = new javax.swing.JLabel();
        book_quantity = new app.bolivia.swing.JCTextField();
        book_invalid = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        user_id = new app.bolivia.swing.JCTextField();
        user_name = new app.bolivia.swing.JCTextField();
        jLabel27 = new javax.swing.JLabel();
        user_invalid = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_userId = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_bookId = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        issueDate = new rojeru_san.componentes.RSDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dueDate = new rojeru_san.componentes.RSDateChooser();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Voltar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        book_id.setBackground(new java.awt.Color(255, 153, 0));
        book_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        book_id.setForeground(new java.awt.Color(255, 204, 153));
        book_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        book_id.setToolTipText("");
        book_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        book_id.setName(""); // NOI18N
        book_id.setPhColor(new java.awt.Color(255, 255, 255));
        book_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_idActionPerformed(evt);
            }
        });
        jPanel1.add(book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 260, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 90, 110));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Informações do livro");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 500, 110));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Título:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 110));

        book_title.setBackground(new java.awt.Color(255, 153, 0));
        book_title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        book_title.setForeground(new java.awt.Color(255, 204, 153));
        book_title.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        book_title.setToolTipText("");
        book_title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        book_title.setName(""); // NOI18N
        book_title.setPhColor(new java.awt.Color(255, 255, 255));
        book_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_titleActionPerformed(evt);
            }
        });
        jPanel1.add(book_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 260, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Autor:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, 110));

        book_author.setBackground(new java.awt.Color(255, 153, 0));
        book_author.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        book_author.setForeground(new java.awt.Color(255, 204, 153));
        book_author.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        book_author.setToolTipText("");
        book_author.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        book_author.setName(""); // NOI18N
        book_author.setPhColor(new java.awt.Color(255, 255, 255));
        book_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_authorActionPerformed(evt);
            }
        });
        jPanel1.add(book_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 260, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Quantidade:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, 110));

        book_quantity.setBackground(new java.awt.Color(255, 153, 0));
        book_quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        book_quantity.setForeground(new java.awt.Color(255, 204, 153));
        book_quantity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        book_quantity.setToolTipText("");
        book_quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        book_quantity.setName(""); // NOI18N
        book_quantity.setPhColor(new java.awt.Color(255, 255, 255));
        book_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_quantityActionPerformed(evt);
            }
        });
        jPanel1.add(book_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 260, 30));

        book_invalid.setBackground(new java.awt.Color(153, 0, 153));
        book_invalid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        book_invalid.setForeground(new java.awt.Color(153, 0, 153));
        book_invalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(book_invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 490, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 830));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, -20, 610, 110));

        jPanel3.setBackground(new java.awt.Color(153, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Informações do usuário");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 490, 110));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("ID:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 90, 110));

        user_id.setBackground(new java.awt.Color(153, 0, 153));
        user_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        user_id.setForeground(new java.awt.Color(204, 153, 255));
        user_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        user_id.setToolTipText("");
        user_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user_id.setName(""); // NOI18N
        user_id.setPhColor(new java.awt.Color(255, 255, 255));
        user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_idActionPerformed(evt);
            }
        });
        jPanel3.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 260, 30));

        user_name.setBackground(new java.awt.Color(153, 0, 153));
        user_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        user_name.setForeground(new java.awt.Color(204, 153, 255));
        user_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        user_name.setToolTipText("");
        user_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user_name.setName(""); // NOI18N
        user_name.setPhColor(new java.awt.Color(255, 255, 255));
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        jPanel3.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 260, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Nome:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 90, 110));

        user_invalid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user_invalid.setForeground(new java.awt.Color(255, 153, 0));
        user_invalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(user_invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 490, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 830));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        jLabel19.setText("Emprestar Livro");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 530, 110));

        txt_userId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 153)));
        txt_userId.setForeground(new java.awt.Color(153, 0, 153));
        txt_userId.setToolTipText("");
        txt_userId.setName(""); // NOI18N
        txt_userId.setPhColor(new java.awt.Color(153, 0, 153));
        txt_userId.setPlaceholder("Digite o id do usuário...");
        txt_userId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_userIdFocusLost(evt);
            }
        });
        txt_userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userIdActionPerformed(evt);
            }
        });
        jPanel2.add(txt_userId, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 300, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Id do usuário:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 150, 50));

        txt_bookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 153)));
        txt_bookId.setForeground(new java.awt.Color(153, 0, 153));
        txt_bookId.setToolTipText("");
        txt_bookId.setName(""); // NOI18N
        txt_bookId.setPhColor(new java.awt.Color(153, 0, 153));
        txt_bookId.setPlaceholder("Digite o id do livro...");
        txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookIdFocusLost(evt);
            }
        });
        txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIdActionPerformed(evt);
            }
        });
        jPanel2.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 300, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Empréstimo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 150, 30));

        issueDate.setColorBackground(new java.awt.Color(153, 0, 153));
        issueDate.setColorButtonHover(new java.awt.Color(153, 0, 153));
        issueDate.setColorForeground(new java.awt.Color(153, 0, 153));
        issueDate.setPlaceholder("Selecione a data");
        jPanel2.add(issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 320, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Id do livro:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 150, 50));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 153));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Data de");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 130, 50));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 153));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Devolução");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 120, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 153));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Data de");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 110, 50));

        dueDate.setColorBackground(new java.awt.Color(153, 0, 153));
        dueDate.setColorButtonHover(new java.awt.Color(153, 0, 153));
        dueDate.setColorForeground(new java.awt.Color(153, 0, 153));
        dueDate.setPlaceholder("Selecione a data");
        jPanel2.add(dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 320, -1));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(164, 57, 164));
        rSMaterialButtonCircle2.setText("Enviar");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 330, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 1030, 830));

        setSize(new java.awt.Dimension(1523, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void book_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_idActionPerformed

    private void book_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_titleActionPerformed

    private void book_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_authorActionPerformed

    private void book_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_quantityActionPerformed

    private void txt_userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userIdActionPerformed

    private void txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIdActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        if (book_quantity.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Esse livro não está disponível!");
        } else {
            if (issueBook() == 1) {
                JOptionPane.showMessageDialog(this, "Livro emprestado com sucesso!");
                updateBookCount();
            } else {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro.");
            }
        }
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void txt_userIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userIdFocusLost
        // TODO add your handling code here:
        if (!txt_userId.getText().equals("")) {
            getUserDetails();
        }
    }//GEN-LAST:event_txt_userIdFocusLost

    private void txt_bookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIdFocusLost
        // TODO add your handling code here:
        if (!txt_bookId.getText().equals("")) {
            getBookDetails();
        }
    }//GEN-LAST:event_txt_bookIdFocusLost

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField book_author;
    private app.bolivia.swing.JCTextField book_id;
    private javax.swing.JLabel book_invalid;
    private app.bolivia.swing.JCTextField book_quantity;
    private app.bolivia.swing.JCTextField book_title;
    private rojeru_san.componentes.RSDateChooser dueDate;
    private rojeru_san.componentes.RSDateChooser issueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private app.bolivia.swing.JCTextField txt_bookId;
    private app.bolivia.swing.JCTextField txt_userId;
    private app.bolivia.swing.JCTextField user_id;
    private javax.swing.JLabel user_invalid;
    private app.bolivia.swing.JCTextField user_name;
    // End of variables declaration//GEN-END:variables
}
