/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ayame
 */
public class ManageUsers extends javax.swing.JFrame {

    /** 
     * Creates new form ManageBooks
     */
    private String nome;
    private int id;

    DefaultTableModel model;
    
    public ManageUsers() {
        initComponents();
        userDetaisToTable();
    }
    
    public void userDetaisToTable() {
        clearTable();
        
        try {
            Connection con = ConexaoBanco.getConnection();
            
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select * from user_details");
            
            while(rs.next()) {
                String userId = rs.getString("user_id");
                String userName = rs.getString("name");
                
                Object[] obj = {userId, userName};
                
                model = (DefaultTableModel) userDetails.getModel();
                model.addRow(obj);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public int addUser() {
        this.nome = user_name.getText();
        this.id = Integer.parseInt(user_id.getText());
        
        try {
            Connection con = ConexaoBanco.getConnection();
            
            String query = "insert into user_details values(?, ?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, id);
            pst.setString(2, nome);
            
            int rowCount = pst.executeUpdate();
            
            if (rowCount > 0) {
                return 1;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return 0;
    }
    
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) userDetails.getModel();
        model.setRowCount(0);
    }

    public int updateUser() {
        this.nome = user_name.getText();
        this.id = Integer.parseInt(user_id.getText());
        
        try {
            Connection con = ConexaoBanco.getConnection();
            
            String query = "update user_details set name = ? where user_id = ?";
            
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nome);
            pst.setInt(2, id);
            
            int rowCount = pst.executeUpdate();
            
            if (rowCount > 0) {
                return 1;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return 0;
    }
    
    public int deleteUser() {
        this.id = Integer.parseInt(user_id.getText());
        
        try {
            Connection con = ConexaoBanco.getConnection();
            
            String query = "delete from user_details where user_id = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, id);
            
            int rowCount = pst.executeUpdate();
            
            if (rowCount > 0) {
                return 1;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return 0;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user_id = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        user_name = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle4 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle6 = new rojerusan.RSMaterialButtonCircle();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userDetails = new rojeru_san.complementos.RSTableMetro();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Voltar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 60, 100));

        user_id.setBackground(new java.awt.Color(255, 153, 0));
        user_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        user_id.setForeground(new java.awt.Color(255, 255, 255));
        user_id.setToolTipText("");
        user_id.setName(""); // NOI18N
        user_id.setPhColor(new java.awt.Color(255, 255, 255));
        user_id.setPlaceholder("Digite o ID do usuário...");
        jPanel1.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 300, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Nome do usuário");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 460, 110));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 60, 100));

        user_name.setBackground(new java.awt.Color(255, 153, 0));
        user_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        user_name.setForeground(new java.awt.Color(255, 255, 255));
        user_name.setToolTipText("");
        user_name.setName(""); // NOI18N
        user_name.setPhColor(new java.awt.Color(255, 255, 255));
        user_name.setPlaceholder("Digite o nome do usuário...");
        jPanel1.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 300, -1));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(153, 0, 153));
        rSMaterialButtonCircle3.setText("remover");
        rSMaterialButtonCircle3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle3MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 140, 80));

        rSMaterialButtonCircle4.setBackground(new java.awt.Color(153, 0, 153));
        rSMaterialButtonCircle4.setText("Adicionar");
        rSMaterialButtonCircle4.setMargin(new java.awt.Insets(2, 14, 3, 10));
        rSMaterialButtonCircle4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle4MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 140, 80));

        rSMaterialButtonCircle6.setBackground(new java.awt.Color(153, 0, 153));
        rSMaterialButtonCircle6.setText("atualizar");
        rSMaterialButtonCircle6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle6MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 140, 80));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Id do usuário");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 460, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 830));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -20, 620, 110));

        userDetails.setBackground(new java.awt.Color(240, 240, 240));
        userDetails.setForeground(new java.awt.Color(255, 255, 255));
        userDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        userDetails.setColorBackgoundHead(new java.awt.Color(153, 0, 153));
        userDetails.setColorBordeFilas(new java.awt.Color(255, 153, 0));
        userDetails.setColorBordeHead(new java.awt.Color(153, 0, 153));
        userDetails.setColorFilasBackgound1(new java.awt.Color(240, 240, 240));
        userDetails.setColorFilasBackgound2(new java.awt.Color(240, 240, 240));
        userDetails.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        userDetails.setRowHeight(27);
        userDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userDetails);
        if (userDetails.getColumnModel().getColumnCount() > 0) {
            userDetails.getColumnModel().getColumn(0).setResizable(false);
            userDetails.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 720, 270));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Student_Male_100px.png"))); // NOI18N
        jLabel9.setText("Organizar Usuários");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 720, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 970, 830));

        setSize(new java.awt.Dimension(1523, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void rSMaterialButtonCircle3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle3MouseClicked

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        if (deleteUser() == 1) {
            JOptionPane.showMessageDialog(this, "Removido com sucesso");
            userDetaisToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void rSMaterialButtonCircle4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle4MouseClicked

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        // TODO add your handling code here:
        if (addUser() == 1) {
            JOptionPane.showMessageDialog(this, "Adicionado com sucesso");
            userDetaisToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void rSMaterialButtonCircle6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle6MouseClicked

    private void rSMaterialButtonCircle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle6ActionPerformed
        // TODO add your handling code here:
        if (updateUser() == 1) {
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
            userDetaisToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle6ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void userDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetailsMouseClicked
        // TODO add your handling code here:
        /*int no = userDetails.getSelectedRow();
        TableModel model = userDetails.getModel();
        
        user_id.setText(model.getValueAt(no, 0).toString());
        book_title.setText(model.getValueAt(no, 1).toString());
        user_name.setText(model.getValueAt(no, 2).toString());
        book_quantity.setText(model.getValueAt(no, 3).toString()); */
    }//GEN-LAST:event_userDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle6;
    private rojeru_san.complementos.RSTableMetro userDetails;
    private app.bolivia.swing.JCTextField user_id;
    private app.bolivia.swing.JCTextField user_name;
    // End of variables declaration//GEN-END:variables
}
